name: ci

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo "USER=romancin" >> $GITHUB_ENV
          echo "REPO=luadch" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image (master branch)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.USER }}/${{ env.REPO }}:${{ env.VERSION }}
            ${{ env.USER }}/${{ env.REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
        if: github.ref == 'refs/heads/master'
      - name: Build Docker Image (develop branch)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.USER }}/${{ env.REPO }}:develop-${{ env.VERSION }}
            ${{ env.USER }}/${{ env.REPO }}:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
        if: github.ref == 'refs/heads/develop'
  update-docherhub-readme:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set variables
        run: |
          echo "USER=romancin" >> $GITHUB_ENV
          echo "REPO=luadch" >> $GITHUB_ENV
        working-directory: ./
      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.USER }}/${{ env.REPO }}
          #short-description: ${{ github.event.repository.description }}
